[package]
name = "alumina"
version = "0.1.0"
authors = ["J. Millard <millard.jn@gmail.com>"]
description = "An Experimental Deep Learning Library"
repository = "https://github.com/millardjn/alumina"
keywords = ["Neural", "Network", "Machine", "Deep", "Learning"]
license = "MIT"


[features]
default = ["mnist", "images"]
mnist = ["byteorder"]
images = ["image"]


[dependencies]
clippy = {version = "*", optional = true}
ndarray = "0.10"
walkdir = "1"
error-chain = "0.11"
odds = "0.2.25"
smallvec = "0.4"
rand = "0.3"
byteorder = {version = "1.0", optional = true}
image = {version = "0.14", optional = true}
num_cpus = "1.6"
threadpool = "1.3"
lazy_static = "0.2"
typenum = "1.9"
typenum_loops = "0.3"
generic-array = "0.8"
scoped_threadpool = "0.1.7"
ordermap = "0.2"
matches = "0.1"
arrayvec = "0.4"

[dependencies.matrixmultiply_mt]
path = "D:/Repositories/matrixmultiply_mt"
#matrixmultiply_mt = "0.1"
#matrixmultiply_mt = {path = "D:/Repositories/matrixmultiply_mt"}

[dev-dependencies]
bytevec = "0.2.0"
image = "0.14"

[lib]
name = "alumina"