[package]
name = "alumina"
version = "0.1.0"
authors = ["J. Millard <millard.jn@gmail.com>"]
description = "An Experimental Deep Learning Library"
repository = "https://github.com/millardjn/alumina"
keywords = ["Neural", "Network", "Machine", "Deep", "Learning"]
license = "MIT"


[features]
default = ["mnist", "images"]
mnist = ["byteorder"]
images = ["image"]


[dependencies]
clippy = {version = "*", optional = true}
ndarray = "0.9"
walkdir = "1"
error-chain = "0.10"
odds = "0.2.25"
smallvec = "0.3"
rand = "0.3"
byteorder = {version = "1.0", optional = true}
image = {version = "0.12", optional = true}

[dependencies.matrixmultiply_mt]
path = "D:/Repositories/matrixmultiply_mt"
#matrixmultiply_mt = "0.1"
#matrixmultiply_mt = {path = "D:/Repositories/matrixmultiply_mt"}

[dev-dependencies]
bytevec = "0.2.0"
image = "0.12"

[lib]
name = "alumina"